api/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('get-student/<str:mat>/',views.getStudent, name='get-student'),
    path('create-record/',views.createRecord, name='create-record'),
]

base/urls.py
from django.urls import path
from . import views
app_name='base'
urlpatterns = [
    path('',views.dashboard, name='dashboard'),
    path('ajouter-etudiants/', views.addStudent, name='add_student'),
    path('etudiants/', views.student, name='student'),
    path('sup-etudiants/', views.deleteStudents, name='sup_etudiants'),
    path('ajouter-domaine/',views.addDomaine, name='ajouter-domaine'),
    path('ajouter-filiere/',views.addFiliere, name='ajouter-filiere'),
    path('ajouter-image/',views.addImage, name='ajouter-filiere'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/', include('api.urls')),
    path('', include('users.urls')),
]

handler404 = "project.views.page_not_found_view"

users/urls.py
from django.urls import path
from . import views
app_name = 'users'
urlpatterns = [
    path('login/', views.user_login, name='user_login' ),
    path('logout/', views.user_logout, name='user_logout'),
    path('register/', views.user_register, name='user_register'),
]

templates/footer.html
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright &copy; Your Website 2021</span>
    </div>
  </div>
</footer>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link
      href="{% static 'vendor/fontawesome-free/css/all.min.css' %}"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
      rel="stylesheet"
    />

    <!-- Custom styles for this template-->
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet" />
  </head>
  
  <body id="page-top">
    {% block main %}
    <!-- Page Wrapper -->
    <div id="wrapper">
      <!-- Sidebar -->
      {% include 'sidebar.html' %}
      <!-- End of Sidebar -->

      <!-- Content Wrapper -->
      <div id="content-wrapper" class="d-flex flex-column">
        <!-- Main Content -->
        <div id="content">
          <!-- Topbar -->
          {% include 'topbar.html' %}
          <!-- End of Topbar -->

          <!-- Begin Page Content -->
          <div class="container-fluid">
            <!--Message section-->
            {% if messages %}
            <!---->
            {% for message in messages %}
            <!-- #region -->
            {% if message.tags == 'error' %}
            <!-- #region -->
            <div
              class="alert alert-danger alert-dismissible fade show"
              role="alert"
            >
              {{ message|safe }}
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% elif message.tags == 'success' %}
            <div
              class="alert alert-success alert-dismissible fade show"
              role="alert"
            >
              {{ message|safe }}
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% else %}
            <div
              class="alert alert-warning alert-dismissible fade show"
              role="alert"
            >
              {{ message|safe }}
              <button
                type="button"
                class="close"
                data-dismiss="alert"
                aria-label="Close"
              >
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <!-- #region -->
            {% endif %}
            <!-- #region -->
            {% endfor %}
            <!-- #region -->
            {% endif %}
            <!-- Page Heading -->
            {% block heading %}
            <!-- <div
              class="d-sm-flex align-items-center justify-content-between mb-4"
            >
              <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>
              <a
                href="#"
                class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"
                ><i class="fas fa-download fa-sm text-white-50"></i> Generate
                Report</a
              >
            </div> -->
            {% endblock %} {% block content %}{% endblock %}
          </div>
          <!-- /.container-fluid -->
        </div>
        <!-- End of Main Content -->

        <!-- Footer -->
        {% include 'footer.html' %}
        <!-- End of Footer -->
      </div>
      <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal
    <div
      class="modal fade"
      id="logoutModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalLabel"
      aria-hidden="true"
    >
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
            <button
              class="close"
              type="button"
              data-dismiss="modal"
              aria-label="Close"
            >
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">
            Select "Logout" below if you are ready to end your current session.
          </div>
          <div class="modal-footer">
            <button
              class="btn btn-secondary"
              type="button"
              data-dismiss="modal"
            >
              Cancel
            </button>
            <a class="btn btn-primary" href="login.html">Logout</a>
          </div>
        </div>
      </div>
    </div> -->

    <!-- Bootstrap core JavaScript-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Core plugin JavaScript-->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>

    <!-- Custom scripts for all pages-->
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>

    <!-- Page level plugins -->
    <script src="{% static 'vendor/chart.js/Chart.min.js' %}"></script>

    <!-- Page level custom scripts -->
    <script src="{% static 'js/demo/chart-area-demo.js' %}"></script>
    <script src="{% static 'js/demo/chart-pie-demo.js' %}"></script>
    {% endblock %}
  </body>
  
</html>

templates/sidebar.html
{% load static %}

<ul
  class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
  id="accordionSidebar"
>
  <!-- Sidebar - Brand -->
  <a
    class="sidebar-brand d-flex align-items-center justify-content-center"
    href="{% url 'base:dashboard' %}"
  >
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-graduation-cap"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0" />

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'base:dashboard' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Tableau De Bord</span></a
    >
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider" />

  <!-- Heading -->
  <div class="sidebar-heading">Interface</div>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'base:student' %}">
      <i class="fas fa-fw fa-users"></i>
      <span>Étudiants</span></a
    >
  </li> 
  {% if not stuff %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'base:add_student' %}">
      <i class="fas fa-fw fa-user-plus"></i>
      <span>Ajouter Étudiant</span></a
    >
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'base:ajouter-domaine' %}">
      <i class="fas fa-fw fa-school"></i>
      <span>Ajouter Domaine</span></a
    >
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'base:ajouter-filiere' %}">
      <i class="fas fa-fw fa-school"></i>
      <span>Ajouter Filière</span></a
    >
  </li>
  {% endif %}

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block" />

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>
</ul>

templates/topbar.html
{% load static %}

<nav
  class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow"
>
  <!-- Sidebar Toggle (Topbar) -->
  <button
    id="sidebarToggleTop"
    class="btn btn-link d-md-none rounded-circle mr-3"
  >
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <form
    class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search"
  >
    <div class="input-group">
      <input
        type="text"
        class="form-control bg-light border-0 small"
        placeholder="Search for..."
        aria-label="Search"
        aria-describedby="basic-addon2"
      />
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">
    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a
        class="nav-link dropdown-toggle"
        href="#"
        id="searchDropdown"
        role="button"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <i class="fas fa-search fa-fw"></i>
      </a>

      <!-- <div class="topbar-divider d-none d-sm-block"></div> -->

      <!-- Nav Item - User Information -->
    </li>

    <li class="nav-item dropdown no-arrow">
      <a
        class="nav-link dropdown-toggle"
        href="#"
        id="userDropdown"
        role="button"
        data-toggle="dropdown"
        aria-haspopup="true"
        aria-expanded="false"
      >
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"
          >{{request.user}}</span
        >
        <img
          class="img-profile rounded-circle"
          src="{% static 'img/undraw_profile.svg' %}"
        />
      </a>
      <!-- Dropdown - User Information -->
      <div
        class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="userDropdown"
      >
        <a
          class="dropdown-item"
          href="{% url 'users:user_logout' %}"
        >
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>
  </ul>
</nav>