api/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('get-student/<str:mat>/',views.getStudent, name='get-student'),
    path('create-record/',views.createRecord, name='create-record'),
]

base/urls.py
from django.urls import path
from . import views
app_name='base'
urlpatterns = [
    path('',views.dashboard, name='dashboard'),
    path('ajouter-etudiants/', views.addStudent, name='add_student'),
    path('etudiants/', views.student, name='student'),
    path('sup-etudiants/', views.deleteStudents, name='sup_etudiants'),
    path('ajouter-domaine/',views.addDomaine, name='ajouter-domaine'),
    path('ajouter-filiere/',views.addFiliere, name='ajouter-filiere'),
    path('ajouter-image/',views.addImage, name='ajouter-filiere'),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/', include('api.urls')),
    path('', include('users.urls')),
]

handler404 = "project.views.page_not_found_view"

base/models.py
from django.db import models

niveaux = [
    ('L1', 'L1'),
    ('L2', 'L2'),
    ('L3', 'L3'),
    ('M1', 'M1'),
    ('M2', 'M2'),
]

class Domaine(models.Model):
    code = models.CharField(max_length=100,primary_key=True)
    nom = models.CharField(max_length=200)
    def __str__(self):
        return self.nom
    
class Filiere(models.Model):
    code = models.CharField(max_length=100,primary_key=True)
    nom =  models.CharField(max_length=200)
    specialite = models.CharField(max_length=200)
    def __str__(self):
        return self.nom

class Etudiant(models.Model):
    mat = models.CharField(max_length=200, primary_key=True)
    nom = models.CharField(max_length=100)
    prenom = models.CharField(max_length=100)
    date_de_naissance = models.DateField()
    domaine = models.ForeignKey(Domaine, on_delete=models.PROTECT, blank=True)
    filiere = models.ForeignKey(Filiere, on_delete=models.PROTECT, blank=True)
    niveau = models.CharField(max_length=20, choices=niveaux, blank=True)
    def __str__(self): 
        return self.mat



class Verifier(models.Model):
    etudiant = models.ForeignKey(Etudiant, on_delete=models.CASCADE)
    date = models.DateField(auto_now=True)
    temp = models.TimeField(auto_now=True)

base/forms.py
from .models import Etudiant, Domaine, Filiere
from django.forms import ModelForm
from django import forms

class DomaineForm(ModelForm):
    class Meta:
        model = Domaine
        fields = '__all__'

class FiliereForm(ModelForm):
    class Meta:
        model = Filiere
        fields = '__all__'

base/views.py
from django.shortcuts import render,redirect
from .importExcel import importExcel 
from .models import Etudiant,Verifier, Domaine, Filiere
from django.contrib import messages
from .forms import DomaineForm, FiliereForm
from .filters import EtudiantFilter, VerifierFilter
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required, permission_required
import os
from django.core.files.storage import default_storage
from django.http import JsonResponse

@login_required(login_url='/login/')
def dashboard(request):
    table_header = ['Mat. Etudiant',
                    'Nom',
                    'Prénom',
                    'Date de naiss.',
                    'Code domaine',
                    'Code filière',
                    'Code niveau',
                    'Date de l\'examen',
                    'Heure de l\'examen']
    records = VerifierFilter(request.GET, queryset=Verifier.objects.all())
    print(request.user.has_perm("base.add_domaine"))
    context={
        'records':records,
        'header':table_header,
        'admin': request.user.groups.filter(name='admins').exists(),
        'stuff':request.user.groups.filter(name='stuff').exists(),
    }
    return render(request, 'base/records.html', context)

@login_required(login_url='/login/')
def student(request):
    table_header = ['Mat. Etudiant',
                    'Nom',
                    'Prénom',
                    'Date de naiss.',
                    'Code domaine',
                    'Code filière',
                    'Code niveau']
    students = EtudiantFilter(request.GET, queryset=Etudiant.objects.all())
    context = {
        'students':students,
        'header':table_header,
        'admin': request.user.groups.filter(name='admins').exists(),
        'stuff':request.user.groups.filter(name='stuff').exists(),
    }
    return render(request, 'base/student.html',context)

@login_required(login_url='/login/')
@permission_required('base.add_etudiant')
def addStudent(request):
    if request.method == 'POST':
        if request.FILES.get('myfile'):
            myfile = request.FILES.get('myfile')
            redir = importExcel(request,myfile)
            if(redir):
                return redirect('base:student')
        else:
            messages.error(request, 'Vous n\'avez pas selction un fichier excel !!! ')
    return render(request, 'base/ajouter-etudiants.html')

@login_required(login_url='/login/')
@permission_required('base.delete_etudiant')
def deleteStudents(request):
    if request.method == 'POST':
        Etudiant.objects.all().delete()
        return redirect('base:student')
    return render(request, 'base/sup_etudiants.html')

@login_required(login_url='/login/')
@permission_required('base.add_domaine')
def addDomaine(request):
    form = DomaineForm()
    if request.method == 'POST':
        try:
            Domaine.objects.create(
                code=request.POST.get('code'),
                nom=request.POST.get('nom')
            )
            return redirect('base:dashboard')
        except IntegrityError as e:
            messages.error(request, 'Le Code <strong>'+str(request.POST.get('code'))+'</strong> est deja existant !!!')
        
    context={
        'form':form
    }
    return render(request, 'base/domaine.html',context)

@login_required(login_url='/login/')
@permission_required('base.add_filiere')
def addFiliere(request):
    form = FiliereForm()
    if request.method == 'POST':
        try:
            Filiere.objects.create(
                code=request.POST.get('code'),
                nom=request.POST.get('nom')
            )
            return redirect('base:dashboard')
        except IntegrityError as e:
            messages.error(request, 'Le Code <strong>'+str(request.POST.get('code'))+'</strong> est deja existant !!!')
        
    context={
        'form':form
    }
    return render(request, 'base/filiere.html',context)


def addImage(request):
    if request.method == 'POST' and request.FILES.get('image'):
            image_file = request.FILES['image']
            file_path = default_storage.save('C:/Users/HP/Desktop/images' + image_file.name, image_file)

            # Obtenez l'URL de l'image en fonction du chemin relatif
            image_url = default_storage.url(file_path)

            return JsonResponse({'image': image_url})
    else:
            return JsonResponse({'message': 'Invalid request.'})
    return render(request, 'home.html')

base/templates/base/ajouter-etudiants.html
{% extends 'index.html' %} {% load static %} {% block content %}
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">
      Ajouter une list d'etudiant avec excel
    </h6>
  </div>
  <div class="card-body">
    <form
      action=""
      method="post"
      enctype="multipart/form-data"
      id="add_student_form"
    >
      {% csrf_token %}
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <span class="input-group-text">Upload</span>
        </div>
        <div class="custom-file">
          <input
            type="file"
            class="custom-file-input"
            id="inputGroupFile01"
            name="myfile"
            accept=".xlsx"
          />
          <label class="custom-file-label" for="inputGroupFile01"
            >Choisir le fichier</label
          >
        </div>
      </div>
      <center>
        <input type="submit" value="Ajouter Étudiant" class="btn btn-success" />
      </center>
    </form>
  </div>
</div>
<br />
<br />
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary">
      Suprimer tout les etudiant
    </h6>
  </div>
  <div class="card-body">
    <form action="" method="post" id="delete_student_form">
      {% csrf_token %}
      <center>
        <a
          href="{% url 'base:sup_etudiants' %}"
          class="btn btn-danger btn-icon-split"
          name="delete_btn"
        >
          <span class="icon text-white-50">
            <i class="fas fa-trash"></i>
          </span>
          <span class="text">Supprimer tous les étudiants</span>
        </a>
      </center>
    </form>
  </div>
</div>
{% endblock %}

base/templates/base/domaine.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% block content %}
<style>
    .set-center {
      height: 75vh;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    #annuler {
      margin-left: 20px;
    }
    .set_width{
        width: 700px;
    }
  </style>
  <div class="set-center">
    <div class="card mb-4 delete">
      <div class="card-header">Ajouter Un Domaine</div>
      <div class="card-body">
        <div class="set_width">
            <center>
                <form action="" method="post">
                  {% csrf_token %}
                  <label for="">Domaine Code:</label>
                  {% render_field form.code class+="form-control" %}
                  <label for="">Domaine:</label>
                  {% render_field form.nom class+="form-control" %}
                  <br>
                  <input type="submit" value="Ajouter" class="btn btn-success" />
                  <a
                    href="{% url 'base:dashboard' %}"
                    class="btn btn-warning"
                    id="annuler"
                    >Annuler</a
                  >
                </form>
              </center>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

base/templates/base/filiere.html
{% extends 'index.html' %}
{% load widget_tweaks %}
{% block content %}
<style>
    .set-center {
      height: 75vh;
      display: flex;
      align-items: center;
      justify-content: center;
    }
    #annuler {
      margin-left: 20px;
    }
    .set_width{
        width: 700px;
    }
  </style>
  <div class="set-center">
    <div class="card mb-4 delete">
      <div class="card-header">Ajouter Une Filière</div>
      <div class="card-body">
        <div class="set_width">
            <center>
                <form action="" method="post">
                  {% csrf_token %}
                  <label for="">Filière Code:</label>
                  {% render_field form.code class+="form-control" %}
                  <label for="">Filière:</label>
                  {% render_field form.nom class+="form-control" %}
                  <br>
                  <input type="submit" value="Ajouter" class="btn btn-success" />
                  <a
                    href="{% url 'base:dashboard' %}"
                    class="btn btn-warning"
                    id="annuler"
                    >Annuler</a
                  >
                </form>
              </center>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

base/templates/base/records.html
{% extends 'index.html' %}
<!-- Loading Widget -->
{% load widget_tweaks %}
<!-- Heading -->
{% block heading %}
<style>
  #filter-btn {
    margin: 10px 0px;
  }
</style>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-6 text-gray-800 m-4">Étudiants</h1>
</div>
{% endblock %} {% block content %}

<div class="card mb-4">
  <center>
    <div class="card-header">Filter</div>
  </center>
  <div class="card-body">
    <form action="#the_list" method="get">
      <div class="row">
        <div class="col">
          <label for="">Matricule:</label>
          {% render_field records.form.mat class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Nom:</label>
          {% render_field records.form.nom class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Prénom:</label>
          {% render_field records.form.prenom class+="form-control" %}
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
          <label for="">Domaine:</label>
          {% render_field records.form.domaine class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Filière:</label>
          {% render_field records.form.filiere class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Niveau:</label>
          {% render_field records.form.niveau class+="form-control" %}
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
          <label for="">L'année De Naissance:</label>
          {% render_field records.form.year class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Le Mois De Naissance:</label>
          {% render_field records.form.month class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Le Jour De Naissance:</label>
          {% render_field records.form.day class+="form-control" %}
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
          <label for="">Date De L'examen :</label>
          {% render_field records.form.date class+="form-control" type='date' %}
        </div>
        <div class="col">
          <label for="">Depuis:</label>
          {% render_field records.form.time_gt class+="form-control" type='time'%}
        </div>
        <div class="col">
          <label for="">Jusqu'à:</label>
          {% render_field records.form.time_lt class+="form-control" type='time'%}
        </div>
      </div>
      <br>
      <center>
        <input type="submit" value="Filtrer" class="btn btn-info" />
        <a href="{% url 'base:dashboard' %}" class="btn btn-warning"
          >Annuler le Filtre</a
        >
      </center>
    </form>
  </div>
</div>

<div class="card shadow mb-4" id="the_list">
  <div class="card-header py-3">
    <center>
      <h6 class="m-0 font-weight-bold text-primary">Tout Les Étudiant</h6>
    </center>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      {% if not records.qs %}
      <center>
        <h1>Aucun enregistrement</h1>
      </center>
      {% else %}
      <table
        class="table table-bordered table-striped"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            {% for head in header %}
            <th>{{head}}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for record in records.qs %}
          <tr>
            <td>{{record.etudiant.mat}}</td>
            <td>{{record.etudiant.nom}}</td>
            <td>{{record.etudiant.prenom}}</td>
            <td>{{record.etudiant.date_de_naissance}}</td>
            <td>{{record.etudiant.domaine}}</td>
            <td>{{record.etudiant.filiere}}</td>
            <td>{{record.etudiant.niveau}}</td>
            <td>{{record.date|date:'d/m/Y'}}</td>
            <td>{{record.temp|date:"G:i"}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

base/templates/base/student.html
{% extends 'index.html' %}
<!-- Loading Widget -->
{% load widget_tweaks %}
<!-- Heading -->
{% block heading %}
<style>
  #filter-btn {
    margin: 10px 0px;
  }
</style>
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-6 text-gray-800 m-4">Étudiants</h1>
  {% if admin %}
  <a href="{% url 'base:add_student' %}" class="btn btn-success btn-icon-split">
    <span class="icon text-white-50">
      <i class="fas fa-user-plus"></i>
    </span>
    <span class="text">Ajouter Étudiant</span>
  </a>
  {% endif %}
</div>
{% endblock %} {% block content %}

<div class="card mb-4">
  <center>
    <div class="card-header">Filter</div>
  </center>
  <div class="card-body">
    <form action="#the_list" method="get">
      <div class="row">
        <div class="col">
          <label for="">Matricule:</label>
          {% render_field students.form.mat class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Nom:</label>
          {% render_field students.form.nom class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Prénom:</label>
          {% render_field students.form.prenom class+="form-control" %}
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
          <label for="">Domaine:</label>
          {% render_field students.form.domaine class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Filière:</label>
          {% render_field students.form.filiere class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Niveau:</label>
          {% render_field students.form.niveau class+="form-control" %}
        </div>
      </div>
      <br />
      <div class="row">
        <div class="col">
          <label for="">L'année De Naissance:</label>
          {% render_field students.form.year class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Le Mois De Naissance:</label>
          {% render_field students.form.month class+="form-control" %}
        </div>
        <div class="col">
          <label for="">Le Jour De Naissance:</label>
          {% render_field students.form.day class+="form-control" %}
        </div>
      </div>
      <br />
      <center>
        <input type="submit" value="Filtrer" class="btn btn-info" />
        <a href="{% url 'base:student' %}" class="btn btn-warning"
          >Annuler le Filtre</a
        >
      </center>
    </form>
  </div>
</div>

<div class="card shadow mb-4" id="the_list">
  <div class="card-header py-3">
    <center>
      <h6 class="m-0 font-weight-bold text-primary">Tout Les Étudiant</h6>
    </center>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      {% if not students.qs %}
      <center>
        <h1>Aucun étudiant</h1>
      </center>
      {% else %}

      <!-- <div class="card mb-4">
        <center>
          <div class="card-header">Filter</div>
        </center>
        <div class="card-body">
          <form action="" method="GET">
            <div class="container">
              <div class="row">
                <div class="col">
                  <label for="mat">Matricule</label>
                  <input type="text" name="mat" id="mat" class="form-control" />
                </div>
                <div class="col">
                  <label for="nom">Nom</label>
                  <input type="text" name="nom" id="nom" class="form-control" />
                </div>
                <div class="col">
                  <label for="prenom">Prénom</label>
                  <input
                    type="text"
                    name="prenom"
                    id="prenom"
                    class="form-control"
                  />
                </div>
              </div>
              <br />
              <div class="row">
                <div class="col">
                  <label for="">Domaine:</label> {{filter_form.domaine}}
                </div>
                <div class="col">
                  <label for="">Filière:</label> {{filter_form.filiere}}
                </div>
                <div class="col">
                  <label for="">Niveau:</label> {{filter_form.niveau}}
                </div>
                <div class="col">
                  <label for="">Date De Naissance:</label>
                  <input
                    type="date"
                    class="form-control"
                    name="date_de_naissance"
                  />
                </div>
              </div>
              <center>
                <input
                  type="submit"
                  value="Filter"
                  class="btn btn-info"
                  id="filter-btn"
                />
              </center>
            </div>
          </form>
        </div>
      </div> -->
      <table
        class="table table-bordered table-striped"
        id="dataTable"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            {% for head in header %}
            <th>{{head}}</th>
            {% endfor %}
          </tr>
        </thead>
        <tbody>
          {% for student in students.qs %}
          <tr>
            <td>{{student.mat}}</td>
            <td>{{student.nom}}</td>
            <td>{{student.prenom}}</td>
            <td>{{student.date_de_naissance|date:'d/m/Y'}}</td>
            <td>{{student.domaine}}</td>
            <td>{{student.filiere}}</td>
            <td>{{student.niveau}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

base/templates/base/sup_etudiants.html
{% extends 'index.html' %} {% block content %}
<style>
  .set-center {
    height: 75vh;
    display: flex;
    align-items: center;
    justify-content: center;
  }
  #annuler {
    margin-left: 20px;
  }
</style>
<div class="set-center">
  <div class="card mb-4 delete">
    <div class="card-header">Default Card Example</div>
    <div class="card-body">
      <center>
        <h1>Êtes-vous sûr de vouloir supprimer tous les étudiants</h1>
        <br />
        <form action="" method="post">
          {% csrf_token %}
          <input type="submit" value="OUI je suis sur" class="btn btn-danger" />
          <a
            href="{% url 'base:add_student' %}"
            class="btn btn-success"
            id="annuler"
            >Annuler</a
          >
        </form>
      </center>
    </div>
  </div>
</div>
{% endblock %}